### ISSUE TITLE
CLI: `oqt create-indicator` should always output a GeoJSON 

### ISSUE THREAD

**Issue by matthiasschaub** [GIScience/ohsome-quality-analyst#10]
**Currently** the output of `oqt create-indicator --infile ...` is a GeoJSON.

**Expected** as output of `oqt create-indicator --dataset ...` is also a GeoJSON. This is not the case.

> The same is true for `oqt create-report`

**Comment by hn437** [comment]
> **Currently** the output of `oqt create-indicator --infile ...` is a GeoJSON.
> 
> **Expected** as output of `oqt create-indicator --dataset ...` is also a GeoJSON. This is not the case.
> 
> > The same is true for `oqt create-report`

Would you reckon the GeoJSON is written for every calculation or only if the `--outfile` flag is set?

**Comment by matthiasschaub** [comment]
The CLI can be used in two ways:
1. Compute an indicator or report and write the results to the dat'abase. This is the case for a feature of a dataset present in the datbase (`dataset`, `feature_id`)
2. Compute an indicator or report and write the results as GeoJSON to disk. This have to be the case if the input to OQT is an GeoJSON with the desired features. But it can also be the case if the input to OQT is the dataset and feature id as described above.

So I am not sure about how to implement this in a simple way.

- If `outfile` has been given an GeoJSON should be written to disk no matter what the input is.
- If `infile` option is given the `outfile` option has to be given also.
- If dataset and feature id is the input to CLI but not outfile simply print a message to stdout if computation of the indicator/report has been successful.
