### ISSUE TITLE
implausible results of "last edit" indicator when applied to non-countable layers

### ISSUE THREAD

**Issue by tyrasd** [GIScience/ohsome-quality-analyst#11]
I was stumbling about very low numbers returned by the `Last Edit for Major Roads` indicator. Some locations even report `0%` even though there is some activity noticeable in the "mapping saturation" curves. Also a quick [overpass query](https://overpass-turbo.eu/s/17gB) confirms that 0% can't possibly the correct result.

![image](https://user-images.githubusercontent.com/1927298/118012765-b1b3b700-b351-11eb-842b-1b433fba0e87.png)

The problem is very likely that [here](https://github.com/GIScience/ohsome-quality-analyst/blob/b8101f3/workers/ohsome_quality_analyst/indicators/last_edit/indicator.py#L60-L67) a "`count`" is divided by a total `length` which of course results in values which are not percentages anymore, and thus cannot be put on a scale from 0% to 100%.

**Comment by matthiasschaub** [comment]
Closing since rewrite of the indicator (https://github.com/GIScience/ohsome-quality-analyst/pull/178) solved this issue.
