### ISSUE TITLE
Do not abort OQT when computing of one indicator fails

### ISSUE THREAD

**Issue by matthiasschaub** [GIScience/ohsome-quality-analyst#119]
There are a couple of cases where OQT computes a number of indicators:
- Input is a GeoJSON FeatureCollection
- Report Creation
- Create all indicators for a dataset in database (currently only `regions`)

When during the computation of a single indicator a error gets raised (e.g. ohsome api timeout) the whole OQT process aborts.

When should we ignore an occurring error and continue with the computation of the other indicators?

**Comment by SamiPetricola** [comment]
That'd be a great improvement.
I would suggest that in any of the three cases, the computation should continue on the other feature/indicator.
Ideally, for the indicator/feature which encounter the error, it should be included in the indicator result of feature:
````
result.label: error
result.description: ohsome api timeout
````

**Comment by matthiasschaub** [comment]
To implement this is not trival.

If we take the first case "Input is a GeoJSON FeatureCollection": If the user uses the API, how does he know that during calculation an error ocured? It could be that the response status code is 200 and a valid GeoJSON, but all result.value attributes are `error`. 

In case of the CLI it is possible to at least print out a warning. So this feature could be implemented for the CLI only.

But this would make the code more complex (Introduce an additional parameter `ignore-error` and differentiate API from CLI requests (First one would raise and error, where the second one will not raise an error). 

As a workaround I suggest to make multiple requests to the OQT API/CLI for eacht Feature in the FeatureCollection

I will close this issue for now. If this continues to be a use-case issue, feel free to reopen it!
