### ISSUE TITLE
Utilize ohsome API `group_by` function to make one request for multiple features

### ISSUE THREAD

**Issue by matthiasschaub** [GIScience/ohsome-quality-analyst#151]
If input to OQT is a FeatureCollection or all features of a specified dataset utilize ohsome API `group by` function to only make one request for all features.

Steps for implementing.

1. `oqt.py`: Decide wether to make a batch request to ohsome API and cache resonse.
2. `ohsome.py`: Check wether a batch request have been made and data is already in cache or a request has to be made.

**Comment by SlowMo24** [comment]
This would vastly improve our user experience (I think): 
![grafik](https://user-images.githubusercontent.com/12476914/153160512-e3cf30cd-f0b3-45f0-ac58-7e194d7d638e.png)
