### ISSUE TITLE
ghspop comparison indicator plot graphs are not complete

### ISSUE THREAD

**Issue by Hagellach37** [GIScience/ohsome-quality-analyst#159]
sometimes it happens that the graph is not correctly plotted. see below:
![image](https://user-images.githubusercontent.com/7045979/130622823-e5d91f46-7036-47c3-994f-6b2d0f11e16a.png)

check with this file:
https://heibox.uni-heidelberg.de/f/149141ee06a14f5f91fb/

**Comment by matthiasschaub** [comment]
Will not fix until implementation of the new [#indicator](https://github.com/GIScience/ohsome-quality-analyst/issues/243)
