### ISSUE TITLE
discuss POI definition

### ISSUE THREAD

**Issue by joker234** [GIScience/ohsome-quality-analyst#161]
By limiting this type to points some elements will be missed which I don't see mentioned in the documentation. I would not include relations but for Heidelberg you miss about 10-20% of elements: https://api.ohsome.org/v1/elements/count/groupBy/type?bboxes=8.67%2C49.39%2C8.71%2C49.42&filter=amenity%3D*%20or%20craft%3D*%20or%20emergency%3D*%20or%20historic%3D*%20or%20leisure%3D*%20or%20man_made%3D*%20or%20office%3D*%20or%20place%3D*%20or%20shop%3D*%20or%20tourism%3D*&format=json&time=2021-08-01

```
{
  "attribution": {
    "url": "https://ohsome.org/copyrights",
    "text": "© OpenStreetMap contributors"
  },
  "apiVersion": "1.6.0",
  "groupByResult": [
    {
      "groupByObject": "NODE",
      "result": [
        {
          "timestamp": "2021-08-01T00:00:00Z",
          "value": 4862
        }
      ]
    },
    {
      "groupByObject": "WAY",
      "result": [
        {
          "timestamp": "2021-08-01T00:00:00Z",
          "value": 941
        }
      ]
    },
    {
      "groupByObject": "RELATION",
      "result": [
        {
          "timestamp": "2021-08-01T00:00:00Z",
          "value": 24
        }
      ]
    }
  ]
}
```

_Originally posted by @SlowMo24 in https://github.com/GIScience/ohsome-quality-analyst/pull/134#discussion_r698359259_

**Comment by joker234** [comment]
You're correct, it shouldn't only contain `geometry:point`. I would suggest `(geometry:point or geometry:polygon)`. I checked `geometry:line` as well, but this includes a lot of features that are imho no POIs like these:
https://www.openstreetmap.org/way/26088966
https://www.openstreetmap.org/way/158025770
https://www.openstreetmap.org/way/312561922
https://www.openstreetmap.org/way/196967009

I would suggest:
 * use only `point` and `polygon` geometries
 * remove `emergency` key, as it isn't a key defining the primary use of a feature, often used on roads
 * remove `place` key as it denotes settlements, not POIs
 * the `man_made` key includes a lot of non-POI features like bridges, masts, embankments, …
 * think how to deal with the `amenity` key as this includes a lot of non-POI features

To get an idea of the complexity of this issue you can have a look at the [POI display OSM Wiki](https://wiki.openstreetmap.org/wiki/POI_display) page.

**Comment by SlowMo24** [comment]
For context: The current definition came from this grouping [here](https://gitlab.gistools.geog.uni-heidelberg.de/giscience/ideal-vgi/automated_quality_indicator_calculation/-/blob/5b3450d14ea68a60925a9afeb3e2f7a1e31b1578/02_fs_calculation/user/diversity/tagGrouping.json) where I needed a simple categorisation of all elements.

I am aware of the flaws of the current definition but do not want to go down the rabbit hole of a more detailed and sophisticated definition. So our project would be happy for any solution you provide but could also stick to the current situation.

**Comment by joker234** [comment]
> further definitions: https://github.com/GIScience/openpoiservice and http://openpoimap.org/

Especially this file could be helpful: https://github.com/GIScience/openpoiservice/blob/master/openpoiservice/server/categories/categories.yml

**Comment by matthiasschaub** [comment]
This issue refers to `ideal_vgi_poi`
https://github.com/GIScience/ohsome-quality-analyst/blob/dcbc1e1f39e4f835fa118318348b8451c383045e/workers/ohsome_quality_analyst/ohsome/layer_definitions.yaml#L246

**Comment by matthiasschaub** [comment]
- [ ] Improve `ideal_vc` as discussed in this issue
- [ ] rename `poi` to `sketchmap_poi` 
- [ ] define new layer definition `poi` according to OMS community

**Comment by matthiasschaub** [comment]
Address comments made to closed PR: https://github.com/GIScience/ohsome-quality-analyst/pull/246
