### ISSUE TITLE
Provide data points for mapping saturation estimate

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/ohsome-quality-analyst#172]
The result for the mapping saturation https://oqt.ohsome.org/api/indicator/MappingSaturation?layerName=building_count&dataset=regions&featureId=3 may also feature the data points (timestamp + building-count) as well as the estimated total and the formula of the fitted function for transparency reasons.

edit: removed hijack

**Comment by joker234** [comment]
> The result for the mapping saturation https://oqt.ohsome.org/api/indicator/MappingSaturation?layerName=building_count&dataset=regions&featureId=3 may also feature the data points (timestamp + building-count) as well as the estimated total and the formula of the fitted function for transparency reasons.

1. I think documentation for all indicators would be nice in which the formula or approach could be described.
2. The data points are already included, see the properties `data.timestamps`, `data.values`, `data.values_normalized`. Or do you miss something else?

> hijack: some descriptions have unesscary \n at the end.

3. true, I made another issue out of that → #174

**Comment by SlowMo24** [comment]
> The data points are already included, see the properties data.timestamps, data.values, data.values_normalized. Or do you miss something else?

I don't see these values in my response: https://oqt.ohsome.org/api/indicator/MappingSaturation?layerName=building_count&dataset=regions&featureId=3

```
properties |  
-- | --
metadata.name | "Mapping Saturation"
metadata.description | "Calculate if mapping has saturated.\n"
layer.name | "Building Count"
layer.description | "All buildings as defined…ed with 'building=*'.\n"
result.timestamp_oqt | "2021-07-15T13:23:40.216356+00:00"
result.timestamp_osm | null
result.label | "yellow"
result.value | 0.5
result.description | "Saturation is reached if… high growth stadium.\n"
result.svg | "<?xml version=\"1.0\" en…ath>\n </defs>\n</svg>\n"
result.data | null
data.time_range | "2008-01-01//P1M"
data.saturation | null
data.growth | null
data.preprocessing_results | null

```

**Comment by joker234** [comment]
I was talking about the current [development version](https://github.com/GIScience/ohsome-quality-analyst/tree/main) and not the stable version:
```json
{
    "apiVersion": "0.5.1",
    "attribution": {
        "text": "\u00a9 OpenStreetMap contributors",
        "url": "https://ohsome.org/copyrights"
    },
    "type": "Feature",
    "geometry": {
        "type": "MultiPolygon",
        "coordinates": […]
    },
    "properties": {
        "metadata.name": "Mapping Saturation",
        "metadata.description": "Calculate if mapping has saturated.\n",
        "layer.name": "Building Count",
        "layer.description": "All buildings as defined by all objects tagged with 'building=*'.\n",
        "result.timestamp_oqt": "2021-09-14T13:46:02.747968+00:00",
        "result.timestamp_osm": "2021-09-01T00:00:00+00:00",
        "result.label": "yellow",
        "result.value": 0.5,
        "result.description": "Saturation is reached if growth is minimal,\nthe value …",
        "result.svg": "<?xml …",
        "result.data": null,
        "data.time_range": "2008-01-01//P1M",
        "data.values": [1.0, 1.0, 1.0, 1.0, 1.0, 4.0, 44.0, 114.0, 226.0, 241.0, …],
        "data.values_normalized": [3.3522174918708724e-05, 3.3522174918708724e-05, 3.3522174918708724e-05, 3.3522174918708724e-05, 3.3522174918708724e-05, 0.0001340886996748349, 0.001474975696423184, 0.003821527940732795, 0.007576011531628172, 0.008078844155408802, …],
        "data.timestamps": ["2008-01-01T00:00:00+00:00", "2008-02-01T00:00:00+00:00", "2008-03-01T00:00:00+00:00", "2008-04-01T00:00:00+00:00", "2008-05-01T00:00:00+00:00", "2008-06-01T00:00:00+00:00", "2008-07-01T00:00:00+00:00", "2008-08-01T00:00:00+00:00", "2008-09-01T00:00:00+00:00", "2008-10-01T00:00:00+00:00", …],
        "data.no_data": false,
        "data.deleted_data": false,
        "data.saturation": 0.9672005797373832,
        "data.growth": 0.03279942026261684
    }
}

**Comment by SlowMo24** [comment]
ok, I see, great!. But the formula is still missing for this specific indicator. While a description in the documentation would be very good, as far as I understand different formulas get fitted to the data so the best choice could be presented in the result. Also a fitted formula is always unique to the data so documentation-only will not prevent the user from fitting multiple models again to recreate and check the `result.value`.

**Comment by matthiasschaub** [comment]
To add to point 2 about the including the data points in the response: It is true that this will be fixed in part in the next release but only for requests with given `bpoly` argument. To fix this issue has already a high priority though: https://github.com/GIScience/ohsome-quality-analyst/issues/145

**Comment by matthiasschaub** [comment]
> ok, I see, great!. But the formula is still missing for this specific indicator. While a description in the documentation would be very good, as far as I understand different formulas get fitted to the data so the best choice could be presented in the result. Also a fitted formula is always unique to the data so documentation-only will not prevent the user from fitting multiple models again to recreate and check the `result.value`.

I created another issue to adress this case. I hope it covers your description:
https://github.com/GIScience/ohsome-quality-analyst/issues/175

**Comment by matthiasschaub** [comment]
Will close this now because of the creation of sub-issues to address issues resulting from this discussion. Please feel free to reopen if I missed something.
