### ISSUE TITLE
remove linebreaks at the end of descriptions

### ISSUE THREAD

**Issue by joker234** [GIScience/ohsome-quality-analyst#174]
Descriptions are including a `\n` at the end. Adding this should be up to the client/renderer and not to the API.

Original issue #172 by @SlowMo24:
> hijack: some descriptions have unesscary \n at the end.

**Comment by karanbihani** [comment]
Hi I am new to Github could you tell me how t start contributing?

**Comment by SlowMo24** [comment]
IMO also the \n in the text itself should be removed. As you said it should be up to the client to render the text.

**Comment by matthiasschaub** [comment]
Fixed in #527
