### ISSUE TITLE
Report real mapping saturation result.value and adjust result.label

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/ohsome-quality-analyst#198]
The `result.value` for the _Mapping Saturation_ parameter is currently only a numeric representation of the `result.label`. This should be changed to represent the actual calculated saturation (`current value/estimated total`). If #145 is addressed `result.value` could be omitted in favour of `estimated.total`. In that case the user could calculate the saturation herself. 

In addition I suggest to replace `result.label` with values like `bad`,`mediocre`, `good` and add `result.color_representation`. 

Related: #172 and #175

**Comment by SlowMo24** [comment]
also can we improve the documentation for the method to assign the `result.label`https://github.com/GIScience/ohsome-quality-analyst/blob/52db4babc9365eb4e1ca38920db9cbf386f7ec22/workers/ohsome_quality_analyst/indicators/mapping_saturation/indicator.py#L15-L19 ?

**Comment by matthiasschaub** [comment]
#170
