### ISSUE TITLE
Add region of "Treptower Tollensewinkel"

### ISSUE THREAD

**Issue by tordans** [GIScience/ohsome-quality-analyst#215]
Would it be possible to add "Treptower Tollensewinkel" https://www.openstreetmap.org/relation/1427697 to the list of analysed regions?

It would be a valuable addition to the [existing analysis on osm-analytics.org](https://osm-analytics.org/#/show/polygon:k~lnAmfxfIkpF~%7DCfd%40~%5B%7DrFhyA_WdhCisDp%5Dyz%40bgBfm%40~iBk%7DAfp%40u%60Jiw%40odBkeBatFbA%7BvCiaHizUajEeyCmyAwdBubFrwEq%7DA~xChvAhdAwz%40%7B%7BA_z%40~gEk%7DBeD_hBkqFfEydAudExmB_fAn%7BEcM%7Cp%40lvApqDb~%40vWdlAt~Doi%40~kI%7CrAyOtq%40jrAnPhdHy%7B%40xeCtr%40qX~f%40t%7DGtcBjtAjwA%7CtGtcA/buildings/recency).

I looked into how to add regions but did not get very far :) …

**Comment by matthiasschaub** [comment]
Hello @tordans, sorry for the late reply. There is currently no way to add a region to those displayed on the website. That is except of adding the regions to the production Geodatabase manually. 

To analyze a custom region with OQT the easiest way is to use our API, where it is possible to upload any GeoJSON (with a size restriction in place). For this have a look at the interactive API interface/docs: https://oqt.ohsome.org/api/docs

But if I understand you correctly you would like to have the results be visualized on our website?

**Comment by tordans** [comment]
@matthiasschaub thanks for your answer and help.

The way I understand it is, that via the API I could get the same data you have on the website, must in a raw format, right?
That would be great!

I tried using the API explorer [with this GeoJSON (Gist)](https://gist.github.com/tordans/b5c73d38c34d34d4e4f6f783835a3d85?short_path=6b4720a) but unfortunately that does not work right away.

Maybe I am missing something simple? – Otherwise I will close this and look into it in detail later.

---

![image](https://user-images.githubusercontent.com/111561/146914775-3018a39c-74a2-434e-b4e8-24a638ad2ab9.png)

Response: 
![image](https://user-images.githubusercontent.com/111561/146914867-22351764-fb73-4c7c-b711-47473c944c92.png)

**Comment by matthiasschaub** [comment]
If I try to copy-past your given GeoJSON as the `bpolys` parameter for a GET request of an report I get following error: `TypeError: NetworkError when attempting to fetch resource`. I am not quite sure why those error occur. Maybe it has something to do with the size of the GeoJSON string. For such large parameter values a POST request is more suitable:
```bash
curl -X 'POST' \
  'https://oqt.ohsome.org/api/report' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "includeSvg": false,
  "name": "SimpleReport",
  "bpolys": {
    "type": "FeatureCollection",
    "generator": "overpass-ide",
    "copyright": "The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.",
    "timestamp": "2021-12-21T09:45:54Z",
    "features": [
      {
        "type": "Feature",
        "properties": {
          "@id": "relation/1427697",
          "admin_level": "7",
          "boundary": "administrative",
          "de:regionalschluessel": "130715163",
          "name": "Treptower Tollensewinkel",
          "name:prefix": "Amt",
          "type": "boundary",
          "wikidata": "Q53771",
          "wikipedia": "de:Amt Treptower Tollensewinkel"
        },
        "geometry": {
          "type": "Polygon",
          "coordinates": [
            ...
          ]
        },
        "id": "relation/1427697"
      }
    ]
  }
}
'
```

With the given GeoJSON this will lead to following response: 
```bash
{
  "apiVersion": "0.7.0",
  "detail": "Input GeoJSON Object is too big. The area should be less than 100 km².",
  "type": "SizeRestrictionError"
}
```

Currently there is a limit on the size of the input GeoJSON we process.

**Comment by matthiasschaub** [comment]
Let me see if we can add the region of Treptower Tollensewinkel to the pre-processed regions in our database for you to retrieve using the website or API.l

**Comment by matthiasschaub** [comment]
Now the region of Treptower Tollensewinkel is a part of the OQT regions. This means it is possible to request indicators or reports for this region like following:
```
curl -X 'GET' \
  'https://oqt.ohsome.org/api/report?name=SimpleReport&includeSvg=false&dataset=regions&featureId=17' \
  -H 'accept: application/json'
```
Note the feature id of Treptower Tollensewinkel is `17`.
Currently indicators and reports for this region is only available using the API. With the next release the region will also be select-able on the OQT website.

 @tordans Enjoy and please get back to us if something does not work!

**Comment by matthiasschaub** [comment]
@tordans, Just a short update: OQT is now integrated into the ohsome dahsboard (https://dashboard.ohsome.org/). This enables computing quality indicators for arbitrary regions. Also, selection of admin boundaries of several levels are possible ("Treptower Tollensewinkel" should be in there)
