### ISSUE TITLE
Redefine OQT regions

### ISSUE THREAD

**Issue by matthiasschaub** [GIScience/ohsome-quality-analyst#26]
## Region origin

In the early phase of development on OQT custom regions where defined for which indicators should be computed. The definitions of regions are quite arbitrary as are the boundaries of regions (In many cases a rectangular bbox).

Today those are the regions for which OQT provides pre-computed indicator results through the website to end-users. In fact those are the only regions for which indicator results can be accessed through the website.

In the future available regions should extent to admin boundaries and/or hexagonal cells covering the globe. But for now OQT restricts it to above mentioned custom regions.

## For which regions should OQT provide pre-computed results?

Regions should be heterogeneous:
- Urban and rural regions
- Regions known for good and bad OSM data quality or coverage
- Different size in area
- Geometry should make sense (e.g. Administrative boundary)

Regions should have following attributes:
- name, country, ogc_fid, degree_of_urbanisation, subjective_quality_expectation, description
- _optionally_: description, source (dataset + id + id_field)

## Current regions

Name (geometry) | Subjective quality expectation
--------------- | ------------------------------
Alger biskra | bad
Alger djanet | bad
Alger Kenadsa | medium
Alger tougourt | bad
Antanarivo | ?
CH Basel Stadt | good
CH Lampenberg | good
Dar es salaam | ?
DE Aschaffenburg | good
DE Hornbach | good
DE Schopfheim | good
DE Stuttgart mitte-süd | good
Grec Athen | medium
Heidelberg altstadt | ?
IT genoa | good
jamaica hot project 9142 | ?
JP tokyo | good
Kadoma zimbabwe | ?
Kano city nigeria | ?
Kathmandu | ?
Mali Agarzane | bad
Mali Razelma | bad
Monaco | good
Moroq Fnideq | medium
Muang xay myanmar | ?
Nigeria Lafia | bad
Nigeria lokoja | medium
Niger Kanan Bakache | bad
Niger Zinder small part | good
Phil Manila | medium
Tun Borj Bourguiba | good
Tun douriet | bad
Tun Remada | medium
Tun Sfax part | good
Tun Tunis center | medium
UK London Westminster | good
US NewYork Manhatten Harlem | ?

### Remove 

Name | Subjective quality expectation
--------------- | ------------------------------
Mali Agarzane | bad
Tun douriet | bad
Tun Sfax part | good
Tun Borj Bourguiba | good
Alger biskra | bad
Alger djanet | bad
Alger Kenadsa | medium

### Update (Before)

Name | Subjective quality expectation
--------------- | ------------------------------
Heidelberg altstadt | ?
UK London Westminster | good
Grec Athen | medium
Moroq Fnideq | medium
Mali Razelma | bad
Phil Manila | medium
Tun Tunis center | medium
Tun Remada | medium
Monaco | good
Alger tougourt | bad

### Update (After)

Name (geometry) | Geometry | Description | Subjective Quality Expectation 
--------------- | ------------------------------|---------------|-------------
Heidelberg | NUTs 01m 2021 geometry | nuts_id DE125| good 
London Westminster | NUTs 01m 2021 geometry | nuts_id UKI32 | good 
Southern Athens  | NUTs  01m 2021 geometry | nuts_id EL304 | medium
Morocco Fnidq | GADM Level 4 geometry| gid_4: MAR.14.5.2.1_1 | medium 
Mali Raz El Ma | GADM Level 4 geometry | gid_4: MLI.9.2.6.1_1  | bad 
Philippines Manila | GADM Level 3 geometry | gid_3 PHL.5.16.22_1 | medium 
Tunisia Tunis | GADM Level 1 geometry | gid_1 TUN.23_1 | medium
Tunisia Remada | GADM Level 2 geometry | gid_2 TUN.21.2_1 | bad
Monaco | GADM Level 0 geometry | gid_0 MCO | good
Algeria Touggourt | GADM Level 2 geometry | gid_2 DZA.33.20_1 | bad
Algeria Bechar | GADM Level 2 geometry | gid_2 DZA.7.2_1 | medium

### Add
Name (geometry) | Geometry | Description | Subjective Quality Expectation
--------------- | ------------------------------|-----------|-----------------
Haiti | GADM Level 0 geometry | gid_0 HTI; MapAction Priority Country  | medium?
Brazil Rio de Janeiro | GADM Level 2 geometry | gid_2 BRA.19.67_1 | bad 
Germany Saterland | GADM Level 3 geometry | gid_3 DEU.9.5.13_1 | medium 
Turkey Kangal | GADM Level 2 geometry | gid_2 TUR.72.10_1 | bad

**Comment by matthiasschaub** [comment]
This issue relates also to #6

**Comment by joker234** [comment]
Related to the main issue: I would really like to have a list (maybe as tabular like in the description) of all regions. Maybe we could integrate this into the webpage.
