### ISSUE TITLE
Creation of a report fails when no mapping has happened in the region

### ISSUE THREAD

**Issue by hn437** [GIScience/ohsome-quality-analyst#32]
Creating a report like remote_mapping_level_one calculates the mean value when combining the indicators. However, if no mapping has taken place, the indicators are labeled undefined, and no undefined indicators are considered. Therefore, the mean calculation fails, as it needs at least one input. This error aborts the calculation for all further report creations as well

**Comment by matthiasschaub** [comment]
If the all indicators of a report are undefinied (label=undefinied, value=None), the report should be undefinied as well.
