### ISSUE TITLE
Define same meaningful "core" Layer for the Tags Ratio Indicator

### ISSUE THREAD

**Issue by matthiasschaub** [GIScience/ohsome-quality-analyst#329]
@Hagellach37 your input is much appreciated

**Comment by Hagellach37** [comment]
Hey,

for highways, we could check for `name` and `surface`. These are possible for mainly any street and these are the two most common combinations according to TagInfo as well: https://taginfo.openstreetmap.org/keys/highway#combinations

For buildings it's a bit more complex and not that obvious. We could check if a building has either `building:levels` or `height` attributes. TagInfo: https://taginfo.openstreetmap.org/keys/building#combinations
