### ISSUE TITLE
Add a Report consisting of only the Mapping Saturation Indicator for multiple Layers

### ISSUE THREAD

**Issue by matthiasschaub** [GIScience/ohsome-quality-analyst#377]
Name: Multidimensional Mapping Saturation or Multilevel Mapping Saturation
Layer: TODO

**Comment by lgroe** [comment]
I think there is a grammar issue in the 'yellow' part of the report description: 
    yellow: |
      **The area experiences** a considerable amount of mapping but is still growing.
