### ISSUE TITLE
Layer names in report output

### ISSUE THREAD

**Issue by lgroe** [GIScience/ohsome-quality-analyst#401]
Currently a report output contains the 'descriptive' layer names instead of the layer names that would be passed to a request with the `indicator` endpoint (e.g. the result of the report would contain "Building Count" instead of "building_count". If the results of layers in a report are e.g. to be collected in a dictionary and uploaded into a database, it is easier to use the layer_name instead of the descriptive name. 

As a workaround, the names have to be defined in an additional dictionary: https://gitlab.gistools.geog.uni-heidelberg.de/giscience/ideal-vgi/osm-element-vectorisation/-/blob/oqt_efficiency/src/osm_element_vectorisation/indicators/surrounding/ohsome/oqt.py#L36 

Is there a specific reason why the descriptive layer names are used in report outputs?

**Comment by matthiasschaub** [comment]
Thanks for raising this issue.

Currently the response include those fields:

```
  "properties": {
    "metadata": {
      "name": "Mapping Saturation",
      "description": "Mapping Saturation"
    },
    "layer": {
      "name": "Building Count",
      "description": "All buildings as defined by all objects tagged with 'building=*'.\n"
    },
```

Until recently we did not make clear distinctions between the key and name of an Indicator/Report/Layer (e.g. Building Count vs. building_count). 
With the next release this will change at least for the layer object. Distinction between name and key for Indicators and Reports  will follow.

From the next release on the response will look like:

```
  "properties": {
    "metadata": {
      "name": "Mapping Saturation",
      "description": "Mapping Saturation"
    },
    "layer": {
      "key": "building_key",
      "name": "Building Count",
      "description": "All buildings as defined by all objects tagged with 'building=*'.\n"
    },
```

**Comment by matthiasschaub** [comment]
- [ ] differentate and inlcude key and name in API reponse for
  - [ ] Layer
  - [ ] Indicator
  - [ ] Report
