### ISSUE TITLE
rename 'layer' to 'topic' 

### ISSUE THREAD

**Issue by matthiasschaub** [GIScience/ohsome-quality-analyst#406]
ohsomeHeX refers to OSM features of a certain type and with certain tags as 'topic'. OQT refers to those features as 'layer'

I would argue 'topic' fits better then 'layer' and it would be nice if ohsomeHeX and OQT are using the same terminology.

Also every layer uses the `elements` endpoint. This could be simplified and the name 'endpoint' renamed to 'measure' (consitent with ohsome Dahsboard).

Related to https://github.com/GIScience/ohsome-quality-analyst/issues/50

**Comment by joker234** [comment]
Since #521 (and other) changed the naming from layer to topic, I'll close this issue.
