### ISSUE TITLE
Following matplotlib guidelines when using it on a web server by not using pyplot

### ISSUE THREAD

**Issue by matthiasschaub** [GIScience/ohsome-quality-analyst#486]
See #487 for possible problems which arise by using pyplot the way OQT uses it currently.

## matplotlib references

- [Embedding in a web application server (Flask)](https://matplotlib.org/stable/gallery/user_interfaces/web_application_server_sgskip.html#embedding-in-a-web-application-server-flask)
- [Backends](https://matplotlib.org/stable/users/explain/backends.html)
- [Work with threads](https://matplotlib.org/stable/users/faq/howto_faq.html#work-with-threads)
    - relevant for running tests using pytest and possible for FastAPI & async/await

**Comment by joker234** [comment]
Will become irrelevant because of the decision to use plotly in the future.
