### ISSUE TITLE
Currentness Indicator - Meta-Issue

### ISSUE THREAD

**Issue by matthiasschaub** [GIScience/ohsome-quality-analyst#492]
This is a meta-issue to collect issues about the Currentness Indicator.

- #405 
- #508 
- #348
- Improve title
- Improve description
- Improve figure

**Comment by matthiasschaub** [comment]
@Gigaszi would it be helpful to collect ideas about improvements to the Currentness Indicator here? Could you extent on this list?

**Comment by Gigaszi** [comment]
There was an idea to change the calculation from one bucket per year to yearly buckets. This would increase comprehensibility and solve the problem that at the beginning of a year the quality assessment is different than at the end of the year

**Comment by matthiasschaub** [comment]
Use GitHub Projects instead of this meta issue
