### ISSUE TITLE
Add project or namespace attribute to layers and indicators

### ISSUE THREAD

**Issue by matthiasschaub** [GIScience/ohsome-quality-analyst#495]
API endpoints can be queried for project based indicators / layers. E.g. `layers?project=general`

**Comment by matthiasschaub** [comment]
Two open questions:

1. What should be the name of this attribute? project or namespace or something else?
2. What should the response of a request to the API endpoint `/metadata/layers` be?
    - all layers
    - only core layers

**Comment by Gigaszi** [comment]
Maybe the API response could be a dictonary of the namespaces, which then contain all layers of the namespace. On the other hand i don't know whether we should promote the project-specific layers if we cannot prove their usefulness. Nevertheless, there should be a way to find the project-specific layers as well.
