### ISSUE TITLE
Map selection on mobile device

### ISSUE THREAD

**Issue by johnjohndoe** [GIScience/ohsome-quality-analyst#509]
The website looks great on the Android smartphone which I tested with (Pixel 6, Brave browser).

I am however not able to select a region with the touch interface of my smartphone. 

![Screenshot_20230316-094227.png](https://user-images.githubusercontent.com/144518/225562997-ae414043-016b-4744-b25f-7f0204d6fe22.png)

**Comment by matthiasschaub** [comment]
Hello @johnjohndoe, thanks for the feedback! The latest development efforts focused on the back-end and API. The website has been just a prototype to showcase some of OQT. We are currently exploring the possibility to integrate OQT into the [ohsome dashboard](https://ohsome.org/apps/dashboard/) which would make for a much nicer user experience.

That is all to say that we are working on a nice solution for accessing OQT via a website. In the end this effort will make the current site obsolete.

**Comment by matthiasschaub** [comment]
Just a short update: OQT is now integrated into the ohsome dahsboard (https://dashboard.ohsome.org/)

Improvements for mobile devices are planned.
