### ISSUE TITLE
swagger UI shouldn't be loaded from external sources

### ISSUE THREAD

**Issue by joker234** [GIScience/ohsome-quality-analyst#539]
Possible solution, see
* https://github.com/GIScience/heigit-disaster-portal/blob/c791ab312ffc52c68820cf9089d67eb43961d7a5/dap_api/app/app/main.py#L73-L81
* https://github.com/GIScience/heigit-disaster-portal/commit/6a5514cb32bdc8c87a764bdb3684c0560b177156
* https://github.com/GIScience/heigit-disaster-portal/commit/c791ab312ffc52c68820cf9089d67eb43961d7a5

**Comment by matthiasschaub** [comment]
https://github.com/GIScience/ohsome-quality-analyst/issues/391
