### ISSUE TITLE
help function from the CLI is not working in the main branch

### ISSUE THREAD

**Issue by hn437** [GIScience/ohsome-quality-analyst#58]
Trying to execute the command `oqt create-indicator --help` the error 
"AttributeError: 'NoneType' object has no attribute 'upper'" 
occurs instead of printing the help. Same applies for `oqt create-report --help`, but not for all other commands including `oqt create-all-indicators --help`

This bug appears in the main branch

**Comment by Hagellach37** [comment]
I checked and it seems to be related to the `feature_id` parameter.
