### ISSUE TITLE
 How to make one request to `/metadata` to receive indicators belonging to project `sketchmap` and topics marked as `core` and `sketchmap`?

### ISSUE THREAD

**Issue by matthiasschaub** [GIScience/ohsome-quality-analyst#590]
Request to `/metadata/core` yields a list of indicators and topics marked as `core`.

Request to `/metadata/sketchmap` yields a list of indicators and topics marked as `sketchmap`.

 How to make one request to `/metadata` to receive indicators belonging to project `sketchmap` and topics marked as `core` and `sketchmap`?

**Comment by joker234** [comment]
Proposed solution:
1. add the possibility to add multiple projects to indicators and topics
2. add all possible projects to every topic and indicator
3. allow to query for all projects

A future solution could incorporate two other possibilities:
* allow to request multiple projects
* allow to have projects incorporating other projects (i.e. `sketchmap` incorporating all `core` projects)
