### ISSUE TITLE
mapping-saturation: rename "Fitted Data" to something else

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/ohsome-quality-analyst#628]
The term "Fittede Data" is a bit confusing for the saturation curve. How about something like

- raw OSM data
- modelled saturation curve

also we know what has been done (count, area, legth) so the Y axis should be more descriptive than "value".

![Bildschirmfoto vom 2023-06-29 17-18-00](https://github.com/GIScience/ohsome-quality-analyst/assets/12476914/dafc100b-6890-483b-ab50-cbc98c7a208c)

**Comment by SlowMo24** [comment]
ah, and the estimated-total line is missing. The graph actually does not show "medium completeness"

**Comment by matthiasschaub** [comment]
Thanks, for the feedback @SlowMo24 
Second point is beeing adressed here: #588
I created an issue for your last point: #629
