### ISSUE TITLE
currentness: nonsensical attention note in result description text

### ISSUE THREAD

**Issue by matthiasschaub** [GIScience/ohsome-quality-analyst#631]
> Attention: There was no mapping activity after 0 in this region.

Vgl. https://github.com/GIScience/ohsome-quality-analyst/blob/2c6dbecb7bbe054b42ec633e60a83a329a5f5f03/workers/ohsome_quality_analyst/indicators/currentness/indicator.py#L120 

Das Problem ist anscheinend, dass `get_last_edited_year()` (https://github.com/GIScience/ohsome-quality-analyst/blob/2c6dbecb7bbe054b42ec633e60a83a329a5f5f03/workers/ohsome_quality_analyst/indicators/currentness/indicator.py#L189) die Anzahl der Jahre, in denen nichts geändert wurde, zurückgibt. Also macht zum einen bei 0 das "Attention" (und allg. der Hinweis) keinen Sinn und zum anderen könnte man das z.B. so formulieren:

> There was no mapping activity since X years in this region

**Comment by Gigaszi** [comment]
This problem is adressed in this PR #589 .

**Comment by matthiasschaub** [comment]
Thanks for the response. I added this issue to the Closes list in the PR.
